'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeftRight, FileDown, MapPin, Play, ScanLine, Upload, X } from 'lucide-react';
import type { DamageDeltaResult } from '@/types';
import { fileToBase64, formatINR } from '@/lib/utils';

const DEFAULT_BEFORE_IMG = 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop';
const DEFAULT_AFTER_IMG = 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop';
const DEMO_BEFORE = "data:image/svg+xml;charset=utf-8," + encodeURIComponent("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 760'><rect width='1200' height='760' fill='#16201f'/><rect x='80' y='90' width='1040' height='590' fill='#d4c3a5'/><rect x='120' y='120' width='330' height='330' fill='#a5c9d2'/><rect x='485' y='135' width='320' height='210' fill='#d8d2bd'/><rect x='850' y='120' width='190' height='430' fill='#59625c'/><rect x='90' y='560' width='1020' height='120' fill='#6b4c38'/><text x='600' y='720' text-anchor='middle' font-family='monospace' font-size='24' fill='#e8e0d4'>MOVE-IN BASELINE · 04 MAY 2025</text></svg>");
const DEMO_AFTER = "data:image/svg+xml;charset=utf-8," + encodeURIComponent("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 760'><rect width='1200' height='760' fill='#16201f'/><rect x='80' y='90' width='1040' height='590' fill='#d4c3a5'/><rect x='120' y='120' width='330' height='330' fill='#a5c9d2'/><rect x='485' y='135' width='320' height='210' fill='#d8d2bd'/><rect x='850' y='120' width='190' height='430' fill='#59625c'/><rect x='90' y='560' width='1020' height='120' fill='#6b4c38'/><path d='M520 300 L600 355 L558 430 L510 390 Z' fill='#503c34'/><path d='M905 555 L1000 610' stroke='#2a2623' stroke-width='14'/><text x='600' y='720' text-anchor='middle' font-family='monospace' font-size='24' fill='#e8e0d4'>MOVE-OUT EVIDENCE · 18 APR 2026</text></svg>");
type EvidenceSide = 'before' | 'after';
type CaseDetails = { address: string; tenant: string; deposit: number };
const markers = [{ left: '47%', top: '48%' }, { left: '79%', top: '75%' }];

function EvidenceLabel({ side }: { side: EvidenceSide }) { return <span className={`rg-evidence-label ${side === 'before' ? 'rg-evidence-label--baseline' : 'rg-evidence-label--exit'}`}>{side === 'before' ? 'MOVE-IN · BASELINE' : 'MOVE-OUT · EXIT EVIDENCE'}</span>; }

export function BeforeAfterInspector() {
  const [position, setPosition] = useState(50); const [beforeImage, setBeforeImage] = useState(DEFAULT_BEFORE_IMG); const [afterImage, setAfterImage] = useState(DEFAULT_AFTER_IMG);
  const [beforeFile, setBeforeFile] = useState<File | null>(null); const [afterFile, setAfterFile] = useState<File | null>(null); const [isLoading, setIsLoading] = useState(false); const [result, setResult] = useState<DamageDeltaResult | null>(null); const [error, setError] = useState<string | null>(null); const [activeMarker, setActiveMarker] = useState<number | null>(null);
  const [details, setDetails] = useState<CaseDetails>({ address: 'Sector 17, Chandigarh · Unit B-204', tenant: 'Aarav Mehta', deposit: 50000 });
  const containerRef = useRef<HTMLDivElement>(null); const objectUrls = useRef<string[]>([]);
  useEffect(() => () => objectUrls.current.forEach(URL.revokeObjectURL), []);
  const updateFromClientX = useCallback((clientX: number) => { const rect = containerRef.current?.getBoundingClientRect(); if (rect) setPosition(Math.max(0, Math.min(100, ((clientX - rect.left) / rect.width) * 100))); }, []);
  function setEvidence(file: File, side: EvidenceSide, preview?: string) { const url = preview ?? URL.createObjectURL(file); if (!preview) objectUrls.current.push(url); setResult(null); setError(null); if (side === 'before') { setBeforeFile(file); setBeforeImage(url); } else { setAfterFile(file); setAfterImage(url); } }
  function onSelect(file: File | undefined, side: EvidenceSide) { if (file) setEvidence(file, side); }
  async function loadDemo() { const toFile = (data: string, name: string) => new File([data], name, { type: 'image/svg+xml' }); setEvidence(toFile(DEMO_BEFORE, 'chandigarh-move-in.svg'), 'before', DEMO_BEFORE); setEvidence(toFile(DEMO_AFTER, 'chandigarh-move-out.svg'), 'after', DEMO_AFTER); setPosition(50); setDetails({ address: 'Sector 17, Chandigarh · Unit B-204', tenant: 'Aarav Mehta', deposit: 50000 }); }
  async function analyze() { if (!beforeFile || !afterFile) return; setIsLoading(true); setError(null); setResult(null); try { const [beforeImageBase64, afterImageBase64] = await Promise.all([fileToBase64(beforeFile), fileToBase64(afterFile)]); const response = await fetch('/api/inspect', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ beforeImageBase64, afterImageBase64, mode: 'delta' }) }); const payload: { data?: DamageDeltaResult; error?: string } = await response.json(); if (!response.ok || !payload.data) throw new Error(payload.error ?? 'Analysis could not be completed.'); setResult(payload.data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Analysis could not be completed.'); } finally { setIsLoading(false); } }
  const setDetail = <K extends keyof CaseDetails>(key: K, value: CaseDetails[K]) => setDetails((current) => ({ ...current, [key]: value }));

  return <section aria-labelledby="comparison-title" className="space-y-5"><div className="rg-section-heading"><div><span className="rg-kicker">EXHIBIT A · IMAGE DELTA</span><h2 id="comparison-title" className="rg-display text-3xl sm:text-4xl">Evidence comparison</h2><p className="rg-copy">A complete case path: establish the baseline, identify only new damage, value it fairly, and produce an audit-ready decision.</p></div><button className="rg-button rg-button--secondary" type="button" onClick={loadDemo}><Play size={14} />LOAD CHANDIGARH DEMO</button></div>
    <fieldset className="rg-case-details"><legend>CASE CONTEXT</legend><label><span><MapPin size={12} />PROPERTY / UNIT</span><input value={details.address} onChange={(event) => setDetail('address', event.target.value)} /></label><label><span>TENANT</span><input value={details.tenant} onChange={(event) => setDetail('tenant', event.target.value)} /></label><label><span>SECURITY DEPOSIT (INR)</span><input type="number" min="0" value={details.deposit} onChange={(event) => setDetail('deposit', Number(event.target.value))} /></label></fieldset>
    <div ref={containerRef} className="rg-comparison" onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); updateFromClientX(event.clientX); }} onPointerMove={(event) => { if (event.currentTarget.hasPointerCapture(event.pointerId)) updateFromClientX(event.clientX); }}><img src={afterImage} alt="Move-out evidence under review" className="rg-comparison-image" draggable={false} /><div className="rg-comparison-before" style={{ width: `${position}%` }}><img src={beforeImage} alt="Move-in baseline evidence" className="rg-comparison-image" draggable={false} /></div><div className="rg-comparison-scrim" /><div className="absolute left-4 top-4"><EvidenceLabel side="before" /></div><div className="absolute right-4 top-4"><EvidenceLabel side="after" /></div>{result?.new_damages.map((damage, index) => <button key={damage.description} type="button" className={`rg-marker ${activeMarker === index ? 'rg-marker--active' : ''}`} style={markers[index] ?? markers[0]} onPointerDown={(event) => event.stopPropagation()} onClick={() => setActiveMarker(activeMarker === index ? null : index)} aria-label={`Show finding ${index + 1}: ${damage.description}`}>{index + 1}</button>)}{activeMarker !== null && result?.new_damages[activeMarker] && <aside className="rg-marker-note"><strong>Finding {activeMarker + 1}</strong><p>{result.new_damages[activeMarker].description}</p><span>{formatINR(result.new_damages[activeMarker].estimated_cost)} · {result.new_damages[activeMarker].severity}</span></aside>}<div className="rg-comparison-divider" style={{ left: `${position}%` }} aria-hidden="true"><div className="rg-tape-handle"><ArrowLeftRight size={16} /></div></div><label className="sr-only" htmlFor="evidence-reveal">Compare move-in and move-out evidence</label><input id="evidence-reveal" className="rg-comparison-range" type="range" min="0" max="100" value={position} onChange={(event) => setPosition(Number(event.target.value))} /></div>
    <div className="grid gap-3 md:grid-cols-2">{(['before', 'after'] as const).map((side) => { const isBefore = side === 'before'; const file = isBefore ? beforeFile : afterFile; return <label key={side} className={`rg-upload ${isBefore ? 'rg-upload--baseline' : 'rg-upload--exit'}`}><Upload size={16} aria-hidden="true" /><span><strong>{file ? file.name : `Attach ${isBefore ? 'move-in' : 'move-out'} photo`}</strong><small>{file ? 'Evidence attached · replace if needed' : isBefore ? 'Baseline condition record' : 'Exit condition record'}</small></span><input type="file" accept="image/*" capture="environment" className="sr-only" onChange={(event) => onSelect(event.target.files?.[0], side)} />{file && <X size={15} aria-hidden="true" />}</label>; })}</div>
    <div className="rg-analysis-bar"><div><span className="rg-kicker">ANALYSIS STATUS</span><p>{beforeFile && afterFile ? 'Paired evidence ready for review.' : 'Attach both records, or load the demo case.'}</p></div><button type="button" onClick={analyze} disabled={!beforeFile || !afterFile || isLoading} className="rg-button rg-button--primary"><ScanLine size={16} />{isLoading ? 'ANALYSING EVIDENCE…' : 'RUN DELTA ANALYSIS'}</button></div>{error && <p role="alert" className="rg-alert">{error}</p>}{result && <DeltaFinding result={result} details={details} />}</section>;
}

function DeltaFinding({ result, details }: { result: DamageDeltaResult; details: CaseDetails }) { const hasLiability = result.total_new_deductible_high > 0; const refundableLow = Math.max(0, details.deposit - result.total_new_deductible_high); const refundableHigh = Math.max(0, details.deposit - result.total_new_deductible_low); return <article className="rg-finding" aria-live="polite"><div className="rg-finding-head"><div><span className="rg-kicker">CASE RG-26-0417 · {details.address.toUpperCase()}</span><h3 className="rg-display text-2xl">{result.overall_condition_change} condition record</h3></div><span className={hasLiability ? 'rg-stamp-rust' : 'rg-stamp-stable'}>{result.tenant_liability} LIABILITY</span></div><p className="rg-copy">{result.summary}</p><div className="grid gap-px sm:grid-cols-3 bg-[var(--rg-line-strong)] border border-[var(--rg-line-strong)]"><div className="rg-finding-metric"><span>NEW FINDINGS</span><strong>{result.new_damages.length}</strong></div><div className="rg-finding-metric"><span>VALUATION RANGE</span><strong>{formatINR(result.total_new_deductible_low)}–{formatINR(result.total_new_deductible_high)}</strong></div><div className="rg-finding-metric"><span>REVIEW CERTAINTY</span><strong>{result.confidence}%</strong></div></div><div className="rg-settlement"><div><span>SECURITY DEPOSIT</span><strong>{formatINR(details.deposit)}</strong></div><div><span>SUGGESTED REFUND TO {details.tenant.toUpperCase()}</span><strong>{formatINR(refundableLow)}–{formatINR(refundableHigh)}</strong></div></div><div className="rg-reasoning"><strong>Why this is fair</strong><p>Only damage that appears in the exit evidence and is not documented in the move-in baseline is included. Existing marks and ordinary wear remain protected. {result.legal_reasoning}</p></div><button type="button" className="rg-button rg-button--secondary" onClick={() => window.print()}><FileDown size={15} />DOWNLOAD AUDIT REPORT (PDF)</button></article>; }
export default BeforeAfterInspector;
