import { ReviewProperty, Review } from "@/types";

export const INITIAL_PROPERTIES: ReviewProperty[] = [
  {
    id: "PROP-STANZA-01",
    name: "Stanza Living Kyoto House",
    type: "PG",
    location: "CyberCity, DLF Phase 3, Gurugram",
    address: "Plot 14, Block U, DLF Phase 3, Sector 24, Gurugram, Haryana 122002",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?q=80&w=1200&auto=format&fit=crop",
    description: "Premium co-living PG for working professionals and students near Cyber Hub with high-speed Wi-Fi, daily housekeeping, and biometric security.",
    pricePerMonthOrNight: "₹18,500 / month",
    googlePlaceId: "ChIJ_stanza_kyoto_001",
    googleMapsUrl: "https://maps.google.com/?cid=10492850291039",
    amenities: ["High-Speed Wi-Fi", "Daily Meals Included", "24/7 Power Backup", "Gym Access", "Biometric Entry", "Launderette"],
  },
  {
    id: "PROP-DLF-HOTEL-02",
    name: "DLF Executive Stays & Suites",
    type: "HOTEL",
    location: "Golf Course Road, Sector 42, Gurugram",
    address: "Tower B, Horizon Centre Enclave, Golf Course Road, Gurugram, Haryana 122002",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1200&auto=format&fit=crop",
    description: "Luxury boutique business hotel offering short-term serviced suites, conference rooms, fine dining, and rooftop lounge.",
    pricePerMonthOrNight: "₹4,200 / night",
    googlePlaceId: "ChIJ_dlf_exec_hotel_002",
    googleMapsUrl: "https://maps.google.com/?cid=20593849102948",
    amenities: ["Rooftop Pool", "Airport Shuttle", "24h Concierge", "Buffet Breakfast", "Conference Rooms", "EV Charging"],
  },
  {
    id: "PROP-ZOLO-03",
    name: "Zolo Stays Prime Heights",
    type: "PG",
    location: "Sector 43, Sushant Lok 1, Gurugram",
    address: "House 204, Sector 43, Near Huda City Metro, Gurugram, Haryana 122009",
    image: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1200&auto=format&fit=crop",
    description: "Modern unisex co-living PG with single and twin sharing rooms, gaming zone, and fully equipped community kitchen.",
    pricePerMonthOrNight: "₹14,000 / month",
    googlePlaceId: "ChIJ_zolo_prime_003",
    googleMapsUrl: "https://maps.google.com/?cid=30492819203948",
    amenities: ["Twin & Single Sharing", "Common Refrigerator", "RO Purifier", "Weekly Linen Change", "CCTV Security", "Study Desks"],
  },
  {
    id: "PROP-BLOOM-04",
    name: "Bloomrooms @ City Centre",
    type: "HOTEL",
    location: "Sector 29, Leisure Valley, Gurugram",
    address: "Plot 85, Sector 29, City Centre Metro Corridor, Gurugram, Haryana 122001",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1200&auto=format&fit=crop",
    description: "Signature yellow-white designer hotel known for cloud beds, grohe rain showers, and central proximity to restaurants and metro.",
    pricePerMonthOrNight: "₹3,100 / night",
    googlePlaceId: "ChIJ_bloom_city_004",
    googleMapsUrl: "https://maps.google.com/?cid=40938291029384",
    amenities: ["Cloud Beds", "Grohe Rain Showers", "iMac Stations", "Cafe Bloom", "Free High-Speed Wi-Fi", "Keycard Elevators"],
  },
];

export const INITIAL_REVIEWS: Review[] = [
  // --- Stanza Living Kyoto House (PG) ---
  {
    id: "REV-RG-101",
    propertyId: "PROP-STANZA-01",
    propertyName: "Stanza Living Kyoto House",
    propertyType: "PG",
    source: "RENTGUARD",
    userId: "aditi-sharma",
    reviewerName: "Aditi Sharma",
    reviewerImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
    rating: 5,
    reviewText: "Stayed here for 11 months during my internship at CyberCity. The RentGuard move-in baseline inspection saved me from being charged for pre-existing scuffs on the wardrobe when I vacated. Food quality is consistently good and biometric security is very reassuring for late nights.",
    stayDate: "Aug 2025 – Jul 2026",
    roomType: "Single Occupancy Room 302",
    verifiedStay: true,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-08-10T14:22:00Z",
    photos: [
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "REV-RG-102",
    propertyId: "PROP-STANZA-01",
    propertyName: "Stanza Living Kyoto House",
    propertyType: "PG",
    source: "RENTGUARD",
    userId: "user-rohan",
    reviewerName: "Rohan Varma",
    rating: 4,
    reviewText: "Clean environment and responsive property warden. Wi-Fi speed is excellent (100+ Mbps). Only minor complaint is occasional queue for the washing machine on Sunday mornings.",
    stayDate: "Jan 2026 – Jun 2026",
    roomType: "Double Sharing 104",
    verifiedStay: true,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-07-28T09:15:00Z",
  },
  {
    id: "REV-GGL-103",
    propertyId: "PROP-STANZA-01",
    propertyName: "Stanza Living Kyoto House",
    propertyType: "PG",
    source: "GOOGLE",
    reviewerName: "Karthik Sundaram",
    reviewerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
    rating: 4,
    reviewText: "Great location if you work in DLF CyberCity Phase 3. 5 minutes walking from Rapid Metro. Housekeeping staff comes every afternoon without fail.",
    stayDate: "Visited 3 weeks ago",
    verifiedStay: false,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-07-15T11:00:00Z",
    externalReviewId: "g-rev-stanza-103",
    googlePlaceId: "ChIJ_stanza_kyoto_001",
    googleMapsUrl: "https://maps.google.com/?cid=10492850291039",
  },
  {
    id: "REV-GGL-104",
    propertyId: "PROP-STANZA-01",
    propertyName: "Stanza Living Kyoto House",
    propertyType: "PG",
    source: "GOOGLE",
    reviewerName: "Pooja Malhotra",
    reviewerImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
    rating: 5,
    reviewText: "Very safe for women. Security guards are polite, no random visitors allowed after 10 PM without app approval. AC cooling was top notch during peak summer.",
    stayDate: "Visited 1 month ago",
    verifiedStay: false,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-06-30T16:45:00Z",
    externalReviewId: "g-rev-stanza-104",
    googlePlaceId: "ChIJ_stanza_kyoto_001",
    googleMapsUrl: "https://maps.google.com/?cid=10492850291039",
  },
  {
    id: "REV-GGL-105",
    propertyId: "PROP-STANZA-01",
    propertyName: "Stanza Living Kyoto House",
    propertyType: "PG",
    source: "GOOGLE",
    reviewerName: "Arun Nair",
    rating: 3,
    reviewText: "Decent place overall. Food menu could have more variety for South Indian breakfast options. Room size in double sharing is slightly compact.",
    stayDate: "Visited 2 months ago",
    verifiedStay: false,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-05-18T10:12:00Z",
    externalReviewId: "g-rev-stanza-105",
    googlePlaceId: "ChIJ_stanza_kyoto_001",
    googleMapsUrl: "https://maps.google.com/?cid=10492850291039",
  },

  // --- DLF Executive Stays & Suites (Hotel) ---
  {
    id: "REV-RG-201",
    propertyId: "PROP-DLF-HOTEL-02",
    propertyName: "DLF Executive Stays & Suites",
    propertyType: "HOTEL",
    source: "RENTGUARD",
    userId: "user-vikram",
    reviewerName: "Vikram Sengupta",
    reviewerImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
    rating: 5,
    reviewText: "Booked a corporate suite for 2 weeks during client meetings. Impeccably clean, noise isolation from Golf Course Road is 100% effective, and the work desk setup with ergonomic chair made remote working seamless.",
    stayDate: "Stayed Jul 2026",
    roomType: "Executive Suite 412",
    verifiedStay: true,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-08-01T18:30:00Z",
    photos: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=600&auto=format&fit=crop",
    ],
  },
  {
    id: "REV-GGL-202",
    propertyId: "PROP-DLF-HOTEL-02",
    propertyName: "DLF Executive Stays & Suites",
    propertyType: "HOTEL",
    source: "GOOGLE",
    reviewerName: "Deepak Chopra",
    reviewerImage: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=200&auto=format&fit=crop",
    rating: 4,
    reviewText: "Excellent breakfast buffet with fresh bakery items and live egg counter. The rooftop swimming pool has stunning skyline views of Horizon Centre towers.",
    stayDate: "Visited 2 weeks ago",
    verifiedStay: false,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-07-22T08:45:00Z",
    externalReviewId: "g-rev-dlf-202",
    googlePlaceId: "ChIJ_dlf_exec_hotel_002",
    googleMapsUrl: "https://maps.google.com/?cid=20593849102948",
  },
  {
    id: "REV-GGL-203",
    propertyId: "PROP-DLF-HOTEL-02",
    propertyName: "DLF Executive Stays & Suites",
    propertyType: "HOTEL",
    source: "GOOGLE",
    reviewerName: "Meenakshi Joshi",
    rating: 5,
    reviewText: "Check-in took less than 2 minutes. The bell desk assisted with all luggage smoothly and the in-room espresso machine was a delightful touch for morning coffee.",
    stayDate: "Visited 1 month ago",
    verifiedStay: false,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-06-14T19:20:00Z",
    externalReviewId: "g-rev-dlf-203",
    googlePlaceId: "ChIJ_dlf_exec_hotel_002",
    googleMapsUrl: "https://maps.google.com/?cid=20593849102948",
  },

  // --- Zolo Stays Prime Heights (PG) ---
  {
    id: "REV-RG-301",
    propertyId: "PROP-ZOLO-03",
    propertyName: "Zolo Stays Prime Heights",
    propertyType: "PG",
    source: "RENTGUARD",
    userId: "user-ananya",
    reviewerName: "Ananya Deshmukh",
    reviewerImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop",
    rating: 4,
    reviewText: "Great budget friendly PG near Huda City Centre metro. The community manager resolves maintenance requests (like geyser fixing) within 4 hours through the app.",
    stayDate: "Stayed Feb 2026 – May 2026",
    roomType: "Twin Sharing Room 108",
    verifiedStay: true,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-06-05T12:00:00Z",
  },
  {
    id: "REV-GGL-302",
    propertyId: "PROP-ZOLO-03",
    propertyName: "Zolo Stays Prime Heights",
    propertyType: "PG",
    source: "GOOGLE",
    reviewerName: "Sameer Aggarwal",
    rating: 4,
    reviewText: "Affordable and clean. High speed internet is reliable for gaming and remote video calls. Friendly flatmates in the common lounge.",
    stayDate: "Visited 3 weeks ago",
    verifiedStay: false,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-07-12T15:30:00Z",
    externalReviewId: "g-rev-zolo-302",
    googlePlaceId: "ChIJ_zolo_prime_003",
    googleMapsUrl: "https://maps.google.com/?cid=30492819203948",
  },

  // --- Bloomrooms @ City Centre (Hotel) ---
  {
    id: "REV-RG-401",
    propertyId: "PROP-BLOOM-04",
    propertyName: "Bloomrooms @ City Centre",
    propertyType: "HOTEL",
    source: "RENTGUARD",
    userId: "user-siddharth",
    reviewerName: "Siddharth Kaul",
    reviewerImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&auto=format&fit=crop",
    rating: 5,
    reviewText: "The cloud bed is genuinely the most comfortable hotel mattress in this price bracket. Spotless white bathrooms with high water pressure grohe showers. Walking distance from Sector 29 nightlife.",
    stayDate: "Stayed Aug 2026",
    roomType: "Bloom Queen Room 204",
    verifiedStay: true,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-08-18T10:10:00Z",
  },
  {
    id: "REV-GGL-402",
    propertyId: "PROP-BLOOM-04",
    propertyName: "Bloomrooms @ City Centre",
    propertyType: "HOTEL",
    source: "GOOGLE",
    reviewerName: "Elena Rostova",
    reviewerImage: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop",
    rating: 4,
    reviewText: "Loved the signature yellow branding and minimalist room aesthetics. Fast check-in and luggage storage after checkout was very convenient.",
    stayDate: "Visited 1 week ago",
    verifiedStay: false,
    status: "approved",
    reportCount: 0,
    createdAt: "2026-08-12T13:40:00Z",
    externalReviewId: "g-rev-bloom-402",
    googlePlaceId: "ChIJ_bloom_city_004",
    googleMapsUrl: "https://maps.google.com/?cid=40938291029384",
  },
];
